baseURL: https://decred.org/
languageCode: en-us
title: Decred
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
pluralizelisttitles: false

params:
    social_media_links:
        -
            id: matrix
            url: https://decred.org/matrix
        -
            id: discord
            url: https://discordapp.com/invite/GJ2GXfz
        -
            id: github
            url: https://github.com/decred
        -
            id: twitter
            url: https://twitter.com/decredproject
        -
            id: reddit
            url: https://www.reddit.com/r/decred
        -
            id: youtube
            url: https://www.youtube.com/decredchannel
        -
            id: medium
            url: https://medium.com/decred


    js_resources:
        critical:
            - "js/modernizr.custom.min.js"
            - "js/jquery.min.js"
            - "js/decred-v5.js"
            - "js/underscore.min.js"
            - "js/moment.min.js"
            - "js/jquery.cookie.js"
            - "js/platform.min.js"
            - "js/main.js"
        extra:
            - "js/jquery.dataTables.min.js"
            - "js/jquery.waypoints.min.js"
            - "js/jquery.shuffle.js"
            - "js/inview.min.js"
            - "js/main-ex.js"

languages: 
    en:
        weight: 10
        languageName: ENG
        params:
            languageDir: ltr
    zh:
        languageName: 中文
        weight: 20
        params:
            languageDir: ltr
            social_media_links:
                -
                    id: matrix
                    url: https://decred.org/matrix
                -
                    id: discord
                    url: https://discordapp.com/invite/GJ2GXfz
                -
                    id: github
                    url: https://github.com/decred
                -
                    id: reddit
                    url: https://www.reddit.com/r/decred
                -
                    id: qq
                    url: http://qm.qq.com/cgi-bin/qm/qr?k=Jl72I0gE6ggrKzF0PdSayXGLXyIj8od0
                -
                    id: wechat
                    url: https://mp.weixin.qq.com/s/6FY8MR7rUXzou2Cy1-oEfQ
                -
                    id: youku
                    url: https://i.youku.com/decredproject
                -
                    id: chainnode
                    url: https://www.chainnode.com/forum/305
    pt:
        languageName: "PT"
        weight: 50
        params:
                languageDir: ltr
    ar:
        languageName: العَرَبِيَّة
        weight: 90
        params:
            languageDir: rtl
    es:
        languageName: SPA
        weight: 100
        params:
            languageDir: ltr
    de:
        languageName: GER
        weight: 110
        params:
            languageDir: ltr
    pl:
        languageName: POL
        weight: 120
        params:
            languageDir: ltr
