baseURL: https://decred.org/
languageCode: en-us
title: Decred
defaultContentLanguage: en
defaultContentLanguageInSubdir: false

params:
    social_media_links:
    js_resources:
        critical:
            - "js/modernizr.custom.min.js"
            - "js/jquery.min.js"
            - "js/decred-v5.js"
            - "js/pts.min.js"
            - "js/verge.min.js"
            - "js/underscore.min.js"
            - "js/moment.min.js"
            - "js/jquery.cookie.js"
            - "js/anime.min.js"
            - "js/platform.min.js"
            - "js/pts5.js"
            - "js/main.js"
        extra:
            - "js/jquery.dataTables.min.js"
            - "js/jquery.waypoints.min.js"
            - "js/jquery.shuffle.js"
            - "js/inview.min.js"
            - "js/main-ex.js"

languages: 
    en:
        weight: 10
        languageName: ENG
        params:
            languageDir: ltr
    zh:
        languageName: 中文
        weight: 20
        params:
            languageDir: ltr
            social_media_links:
                -
                    id: qq
                    label: qq
                    url: http://weixin.qq.com/r/Njnr8xfEtkrJrVOQ92wk
                -
                    id: wechat
                    label: Wechat
                    url: http://u.wechat.com/MIRs6aSo2eBK9GSYq8ec84Y
                -
                    id: youku
                    label: Youku
                    url: https://i.youku.com/decred
    ko:
        languageName: 한국어
        weight: 30
        params:
            languageDir: ltr
    ja:
        languageName: 日本語
        weight: 40
        params:
            languageDir: ltr
    pt:
        languageName: POR
        weight: 50
        params:
            languageDir: ltr
    ru:
        languageName: RUS
        weight: 60
        params:
            languageDir: ltr
    tr:
        languageName: TUR
        weight: 70
        params:
            languageDir: ltr
    fa:
        languageName: فارسی
        weight: 80
        params:
            languageDir: rtl
    ar:
        languageName: العَرَبِيَّة
        weight: 90
        params:
            languageDir: rtl
    es:
        languageName: SPA
        weight: 100
        params:
            languageDir: ltr
    de:
        languageName: GER
        weight: 110
        params:
            languageDir: ltr
    pl:
        languageName: POL
        weight: 120
        params:
            languageDir: ltr
