baseURL: https://decred.org/
languageCode: en-us
title: Decred
defaultContentLanguage: en
defaultContentLanguageInSubdir: false

params:
    social_media_links:    
        -
            id: slack    
            label: Slack
            url: https://slack.decred.org
        -
            id: discord
            label: Discord
            url: https://discordapp.com/invite/GJ2GXfz
        -
            id: matrix
            label: Matrix
            url: https://decred.org/matrix
        -
            id: github
            label: GitHub
            url: https://github.com/decred
        -
            id: reddit
            label: Reddit
            url: https://www.reddit.com/r/decred
        -
            id: twitter
            label: Twitter
            url: https://twitter.com/decredproject
        -
            id: youtube
            label: YouTube
            url: https://www.youtube.com/decredchannel
        -
            id: medium
            label: Medium
            url: https://medium.com/decred


    js_resources:
        critical:
            - "js/modernizr.custom.min.js"
            - "js/jquery.min.js"
            - "js/decred-v5.js"
            - "js/verge.min.js"
            - "js/underscore.min.js"
            - "js/moment.min.js"
            - "js/jquery.cookie.js"
            - "js/anime.min.js"
            - "js/platform.min.js"
            - "js/main.js"
        extra:
            - "js/jquery.dataTables.min.js"
            - "js/jquery.waypoints.min.js"
            - "js/jquery.shuffle.js"
            - "js/inview.min.js"
            - "js/main-ex.js"

languages: 
    en:
        weight: 10
        languageName: ENG
        params:
            languageDir: ltr
    zh:
        languageName: 中文
        weight: 20
        params:
            languageDir: ltr
            social_media_links:
                -
                    id: slack    
                    label: Slack
                    url: https://slack.decred.org
                -
                    id: discord
                    label: Discord
                    url: https://discordapp.com/invite/GJ2GXfz
                -
                    id: matrix
                    label: Matrix
                    url: https://decred.org/matrix
                -
                    id: github
                    label: GitHub
                    url: https://github.com/decred
                -
                    id: reddit
                    label: Reddit
                    url: https://www.reddit.com/r/decred
                -
                    id: qq
                    label: QQ
                    url: http://qm.qq.com/cgi-bin/qm/qr?k=Jl72I0gE6ggrKzF0PdSayXGLXyIj8od0
                -
                    id: wechat
                    label: WeChat
                    url: https://mp.weixin.qq.com/s/6FY8MR7rUXzou2Cy1-oEfQ
                -
                    id: youku
                    label: Youku
                    url: https://i.youku.com/decredproject
                -
                    id: chainnode
                    label: ChainNode
                    url: https://www.chainnode.com/forum/305
    ko:
        languageName: 한국어
        weight: 30
        params:
            languageDir: ltr
    ja:
        languageName: 日本語
        weight: 40
        params:
            languageDir: ltr
    pt:
        languageName: POR
        weight: 50
        params:
            languageDir: ltr
    ru:
        languageName: RUS
        weight: 60
        params:
            languageDir: ltr
    tr:
        languageName: TUR
        weight: 70
        params:
            languageDir: ltr
    fa:
        languageName: فارسی
        weight: 80
        params:
            languageDir: rtl
    ar:
        languageName: العَرَبِيَّة
        weight: 90
        params:
            languageDir: rtl
    es:
        languageName: SPA
        weight: 100
        params:
            languageDir: ltr
    de:
        languageName: GER
        weight: 110
        params:
            languageDir: ltr
    pl:
        languageName: POL
        weight: 120
        params:
            languageDir: ltr
